FROM python:3.10

# 작업 디렉토리 설정
WORKDIR C:\Users\qkrdm\Euizzangit\MO4E_Devkor\app\fastapi_app

# requirements.txt 파일을 이미지로 복사
COPY requirements.txt .

# 필요한 Python 패키지 설치
RUN pip3 install -r requirements.txt

# 포트 노출
EXPOSE 8000

# 컨테이너 시작 명령어 (예시)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
